PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT * 
WHERE { 
	?dbpediaresource dbo:date "1937-05-06"^^xsd:date .
    ?dbpediaresource foaf:isPrimaryTopicOf ?dbpediaurl2 .
} 