#Numero personas desaparecidas por localidad
SELECT ?localidad (?desaparecidos*100/4881 as ?numDesaparecidos) WHERE{SELECT distinct ?localidad (COUNT(?localidad) as ?desaparecidos) (SUM(?numMuertos) as ?numero) WHERE{
  ?persona rdf:type <http://guerracivileuskadi.eurohelp.es/linkeddata/def/euskadipedia/missing-person>;
<http://dbpedia.org/ontology/birthPlace> ?localidad }GROUP BY ?localidad ORDER BY ?numMuertos} ORDER BY DESC(?desaparecidos) LIMIT 5