#Numero personas desaparecidas por localidad
SELECT ?localidad ?numDesaparecidos WHERE{SELECT distinct ?localidad (COUNT(?localidad) as ?numDesaparecidos) (SUM(?numMuertos) as ?numero) WHERE{
  ?persona rdf:type <http://guerracivileuskadi.eurohelp.es/linkeddata/def/euskadipedia/missing-person>;
<http://dbpedia.org/ontology/birthPlace> ?localidad }GROUP BY ?localidad ORDER BY ?numMuertos} ORDER BY DESC(?numDesaparecidos) LIMIT 10