#numFosasPorProvincia
SELECT distinct ?provincia (COUNT(?provincia) as ?numFosas) WHERE{
  ?fosa rdf:type <http://rdf.muninn-project.org/ontologies/graves#Mass_grave>;
 <http://schema.org/State> ?provincia }GROUP BY ?provincia ORDER BY ?numFosas