#Top ten localidades mas bombardeadas
SELECT ?provincia ?numBombardeos WHERE{SELECT distinct ?provincia (COUNT(?provincia) as ?numBombardeos) (SUM(?numFosas) as ?numero) WHERE{
  ?bombardeo rdf:type <http://dbpedia.org/resource/Aerial_bombing_of_cities>;
 <http://schema.org/location> ?provincia }GROUP BY ?provincia ORDER BY ?numFosas} ORDER BY DESC(?numBombardeos) LIMIT 10