PREFIX mydata: <http://example.com/resource/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX spif: <http://spinrdf.org/spif#>
PREFIX schema: <http://schema.org/>
INSERT{
  GRAPH<http://id.euskadi.eus/catalogo/mass_grave>{
	?mainUri a ?dbpediaMassGraves ;
     a ?ontologiaGraves ;
	schema:City ?Poblacion ;
	schema:State ?uriProvinciaCreada ;
	geo:lat ?Latitud ;
	geo:long ?Longitud .
  }
  } WHERE {
  SERVICE<http://localhost:7200/rdf-bridge/1810998186867>{
	?row a mydata:Row ;
		mydata:Poblacion ?Poblacion ;
  		mydata:PoblacionUri ?PoblacionUri ;
		mydata:Provincia ?Provincia ;
  		mydata:ProvinciaUri ?ProvinciaUri ;
		mydata:Latitud ?Latitud ;
		mydata:Longitud ?Longitud .
  }
  BIND(IRI(spif:buildString("http://id.euskadi.eus/public-sector/history/mass-grave/{?1}-{?2}", ENCODE_FOR_URI(?PoblacionUri) , ENCODE_FOR_URI(?ProvinciaUri))) AS ?mainUri)
    BIND(IRI(spif:buildString("http://datos.gob.es/recurso/sector-publico/territorio/Provincia/{?1}" , ENCODE_FOR_URI(?Provincia))) AS ?uriProvinciaCreada)
  BIND(IRI("http://rdf.muninn-project.org/ontologies/graves#Mass_grave") as ?ontologiaGraves)
  BIND(IRI("http://dbpedia.org/page/Mass_grave") as ?dbpediaMassGraves)


} 