#Query obtiene numero bombardeos
SELECT (SUM(?o) as ?numBombardeos) where {?recurso rdf:type <http://dbpedia.org/resource/Aerial_bombing_of_cities>. ?recurso <http://guerracivileuskadi.eurohelp.es/linkeddata/def/euskadipedia/numerobombardeos> ?o
  }