#Query obtiene numero personas desaparecidas
SELECT (COUNT(distinct ?recurso) AS ?total) where {?recurso rdf:type <http://guerracivileuskadi.eurohelp.es/linkeddata/def/euskadipedia/missing-person> 
  }