PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX geo-pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>
select * 
where { 
	?bombardment dbp:plannedBy dbr:Francoist_Spain .
    ?bombardment geo-pos:lat ?latitude .
    ?bombardment geo-pos:long ?longitude .
    ?bombardment dbo:date ?date .
    ?bombardment schema:location ?location .
}